(function(){function initChatWidget(){const chatToggle=document.getElementById('chatToggle');const chatBox=document.getElementById('chatBox');const chatClose=document.getElementById('chatClose');const chatForm=document.getElementById('chatForm');const successMessage=document.getElementById('successMessage');const newEnquiryBtn=document.getElementById('newEnquiry');const formError=document.getElementById('formError');if(!chatToggle||!chatBox)return;if(chatToggle.dataset.chatInit==='true')return;chatToggle.dataset.chatInit='true';chatToggle.addEventListener('click',function(){chatBox.classList.add('open')});if(chatClose){chatClose.addEventListener('click',function(){chatBox.classList.remove('open')})}
document.addEventListener('click',function(event){if(chatBox.classList.contains('open')){const isClickInside=chatBox.contains(event.target)||chatToggle.contains(event.target);if(!isClickInside){chatBox.classList.remove('open')}}});document.addEventListener('keydown',function(event){if(event.key==='Escape'&&chatBox.classList.contains('open')){chatBox.classList.remove('open')}});function validateEmail(email){const re=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(String(email).toLowerCase())}
function clearErrors(){const errorElements=document.querySelectorAll('.error-message');errorElements.forEach(el=>{el.textContent=''});const inputs=document.querySelectorAll('.form-input, .form-textarea');inputs.forEach(input=>{input.classList.remove('error');input.style.borderColor=''})}
function showError(inputId,message){const errorElement=document.getElementById(inputId+'Error');const inputElement=document.querySelector(`[name="${inputId}"]`);if(errorElement){errorElement.textContent=message}
if(inputElement){inputElement.classList.add('error');inputElement.style.borderColor='#DC2626'}}
function setFormError(message){if(!formError)return;formError.textContent=message}
if(chatForm){chatForm.addEventListener('submit',async function(e){e.preventDefault();clearErrors();setFormError('');const name=chatForm.querySelector('[name="name"]').value.trim();const email=chatForm.querySelector('[name="email"]').value.trim();const subject=chatForm.querySelector('[name="subject"]').value.trim();const message=chatForm.querySelector('[name="message"]').value.trim();let isValid=!0;if(!name){showError('name','Please enter your full name');isValid=!1}
if(!email){showError('email','Please enter your email address');isValid=!1}else if(!validateEmail(email)){showError('email','Please enter a valid email address');isValid=!1}
if(!subject){showError('subject','Please enter a subject for your enquiry');isValid=!1}
if(!message){showError('message','Please enter your message');isValid=!1}else if(message.length<10){showError('message','Please provide more details in your message');isValid=!1}
if(!isValid)return;const submitBtn=chatForm.querySelector('.submit-btn');const originalText=submitBtn?submitBtn.innerHTML:'';if(submitBtn){submitBtn.innerHTML='Sending...';submitBtn.disabled=!0}
try{const formData=new FormData(chatForm);if(!formData.get('enquiryType')){formData.set('enquiryType','Chat Enquiry')}
const response=await fetch('send-mail.php',{method:'POST',body:formData});const result=await response.json().catch(()=>null);if(!response.ok||!result||!result.success){throw new Error((result&&result.message)||'Unable to submit your enquiry. Please try again.')}
chatForm.style.display='none';if(successMessage)successMessage.style.display='block';chatForm.reset();setTimeout(()=>{chatBox.classList.remove('open');setTimeout(()=>{chatForm.style.display='flex';if(successMessage)successMessage.style.display='none'},300)},5000)}catch(error){setFormError(error.message||'Unable to submit your enquiry. Please try again later.')}finally{if(submitBtn){submitBtn.innerHTML=originalText;submitBtn.disabled=!1}}})}
if(newEnquiryBtn){newEnquiryBtn.addEventListener('click',function(){if(chatForm)chatForm.style.display='flex';if(successMessage)successMessage.style.display='none';if(chatForm)chatForm.reset();clearErrors();setFormError('')})}
const formInputs=document.querySelectorAll('.form-input, .form-textarea');formInputs.forEach(input=>{input.addEventListener('input',function(){if(this.classList.contains('error')){this.classList.remove('error');this.style.borderColor=''}
const errorId=this.name+'Error';const errorElement=document.getElementById(errorId);if(errorElement){errorElement.textContent=''}})})}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initChatWidget)}else{initChatWidget()}})()